### ISSUE TITLE
Decoded strings include leading length field

### ISSUE THREAD

**Issue by doug-a-brunner** [rimio/libecbor#17]
When I retrieve a definite string value using `ecbor_get_str()`, the pointer returned via `value` points not to the beginning of the string but to the beginning of the length field. It seems like the only way for the caller to get the beginning of the actual string is to extract the length field's size by `item.size - item.length` and advance the pointer by this amount. Am I missing something here?

**Comment by rimio** [comment]
Hi! Your use case should work fine. Actually, `ecbor_describe` uses the same API to print stuff to stdout and it seems to work, at least on the tests I have so far.

For example you can take a look at the behavior for test 57 of Appendix A of the RFC, which encodes the string "IETF". This is my `gdb` output:

```
Breakpoint 1, print_ecbor_item (item=0x7fffffffe050, level=0, prefix=0x5555555580f7 "") at [redacted]/src/ecbor-describe/ecbor_describe.c:67
67	  mt = ecbor_get_type (item);
Warning: the current language does not match this frame.
$(gdb) n
99	        rc = ecbor_get_length (item, &len);
$(gdb) p item
$1 = (ecbor_item_t *) 0x7fffffffe050
$(gdb) p *item
$2 = {
  type = ECBOR_TYPE_STR,
  value = {
    uinteger = 93824992347329,
    integer = 93824992347329,
    fp32 = 1.47759636e+13,
    fp64 = 4.6355705440133117e-310,
    tag = {
      tag_value = 93824992347329,
      child = 0x0
    },
    string = {
      str = 0x5555555704c1 "IETF",
      n_chunks = 0
    },
    items = 0x5555555704c1 "IETF"
  },
  size = 5,
  length = 4,
  is_indefinite = 0 '\000',
  parent = 0x0,
  child = 0x0,
  next = 0x0,
  index = 0
}
$(gdb) p item->string.str[0]
There is no member named string.
$(gdb) p item->value.string.str[0]
$3 = 73 'I'
$(gdb) n
100	        if (rc != ECBOR_OK) {
$(gdb)
104	        if (ECBOR_IS_INDEFINITE (item)) {
$(gdb)
129	          rc = ecbor_get_str (item, &val);
$(gdb) n
130	          if (rc != ECBOR_OK) {
$(gdb) p rc
$4 = ECBOR_OK
$(gdb) p val
$5 = 0x5555555704c1 "IETF"
$(gdb) p val[0]
$6 = 73 'I'
```

Could you please provide a small reproduction scenario for me to understand the issue better? Please provide the version (or commit hash) you're using.

**Comment by doug-a-brunner** [comment]
@rimio, I'm using version 1.0.2 (7af5787). I found the error only appears when decoding strings that need a separate length byte (length too large to fit in the short count).

As an example, I created a CBOR file with the string "Lorem ipsum dolor sit amet, consectetur adipiscing elit.". In hex form, this is `78384c6f72656d20697073756d20646f6c6f722073697420616d65742c20636f6e73656374657475722061646970697363696e6720656c69742e`. Gzipped so Github will accept it: [test1.cbor.gz](https://github.com/rimio/libecbor/files/11727002/test1.cbor.gz)

Output appears as follows:
```
REDACTED$ bin/ecbor-describe test1.cbor
Reading CBOR from file 'test1.cbor'
CBOR objects:
[STR] len 56 value '8Lorem ipsum dolor sit amet, consectetur adipiscing elit'
```
Expected output would be:
```
[STR] len 56 value 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
```

**Comment by rimio** [comment]
@doug-a-brunner Thanks a lot for the report!

I've just committed fca8388fcad12182bd0406d262c873bbce29fee5 which should fix this. I've added a few test cases for this as well.

Hopefully there's no glaring issue I'm missing, it's been a bit of time since I last did anything CBOR related.
